[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_lambda_events = "0.7.3"
http = "0.2.4"
lambda_http = "0.7.3"
lambda_runtime = "0.7.3"
log = "0.4.14"
simple_logger = "4.0.0"
tokio = "1.6.1"
